project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "posts/**/*.qmd"

website:
  title: "ğŸš„ Jorge Ubirajara Pedreira Junior"
  site-url: https://pedreirajr.github.io/website
  search: true
  open-graph: true
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
        icon: house-door
      - href: publications.qmd
        text: "ğŸ“ Publications"
      - href: codeanddata.qmd
        text: "ğŸ’» Code and Data"
      - href: about.qmd
        text: "ğŸ‘¨ğŸ»â€ğŸ« About me"
  page-footer:
    center: |
      Jorge Ubirajara Pedreira Junior | Powered by [Quarto](https://quarto.org)

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    include-in-header:
      - text: '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">'
    toc: true

editor: visual
