project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "posts/**/*.qmd"

website:
  title: "ðŸš„ Jorge Ubirajara Pedreira Junior"
  site-url: https://pedreirajr.github.io/website
  search: true
  open-graph: true
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: packages.qmd
        text: Packages
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/pedreirajr
      - icon: youtube
        href: https://www.youtube.com/@jorge.ubirajara
      - icon: linkedin
        href: https://www.linkedin.com/in/jorgeubirajara/
      - text: Lattes
        href: http://lattes.cnpq.br/7602862678306492
  page-footer:
    center: |
      Jorge Ubirajara Pedreira Junior | Powered by [Quarto](https://quarto.org)

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true

editor: visual
